# Generated by Django 5.2.13 on 2026-06-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authtoken", "0004_alter_tokenproxy_options"),
        ("openwisp_users", "0023_add_auth_token_permissions_to_admins"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
                "verbose_name": "API key",
                "verbose_name_plural": "API keys",
            },
            bases=("authtoken.token",),
        ),
    ]
