# Generated by Django 5.2.13 on 2026-07-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_users", "0024_apikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationuser",
            name="is_admin",
            field=models.BooleanField(
                default=False, verbose_name="Organization manager"
            ),
        ),
    ]
