# Generated by Django 5.2.16 on 2026-07-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_users", "0026_fix_duplicate_user_id_email_idx_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Records whether the last login used a local password or an external method (eg: SSO, SAML), so password expiration is not enforced for logins that never used the password.",
                max_length=16,
                verbose_name="last login method",
            ),
        ),
    ]
