[tool.coverage.run]
source = ["openwisp_users"]
parallel = true
concurrency = ["multiprocessing"]
omit = [
    "openwisp_users/__init__.py",
    "openwisp_users/accounts/urls.py",
    "*/tests/*",
    "*/migrations/*",
]

[tool.docstrfmt]
extend_exclude = ["**/*.py"]

[tool.isort]
known_third_party = ["django", "allauth"]
known_first_party = ["openwisp_users", "openwisp_utils"]
default_section = "THIRDPARTY"
line_length = 88
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true
force_grid_wrap = 0
