# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('testapp', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='config',
            name='template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='testapp.Template',
            ),
        )
    ]
