# Generated by Django 3.1.12 on 2021-06-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testapp', '0003_multitenancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('address', models.TextField(blank=True, null=True)),
                (
                    'book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='testapp.book'
                    ),
                ),
            ],
        ),
    ]
