# Generated by Django 3.0.8 on 2020-07-23 17:55

from django.db import migrations
from openwisp_users.migrations import allow_admins_change_organization


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_multitenancy'),
    ]

    operations = [migrations.RunPython(allow_admins_change_organization)]
