# Generated by Django 3.2.16 on 2022-12-22 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testapp', '0005_default_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='testapp.shelf',
            ),
        ),
    ]
