# Generated by Django 5.2.1 on 2025-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0006_alter_book_shelf"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="secrets",
            field=models.TextField(blank=True, null=True),
        ),
    ]
